version: '3.9'
services:
  taofpsql-db:
    container_name: taofpsql-db-${APP_ENV:-dev}
    image: adomokos/postgres-pgtap:0.1.0
    restart: always
    ports:
      - 5432:5432
    env_file:
      - ../.env.${APP_ENV:-dev}
    volumes:
      - ./resources/sql/:/docker-entrypoint-initdb.d/
      - ../src:/usr/local/src/
    command: ["postgres", "-c", "log_statement=all"]
